### ISSUE TITLE
Explorer does not show latest data

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#176]
Impact: fresh data (>= 02 Oct) is not shown in OONI Explorer

Timeline UTC:
25 Sep 02:18 `REFRESH MATERIALIZED VIEW` is stuck at legacy postgres DB (ssdams) for unknown reason, stats are not properly updated since that time (including "known blockpages")
02 Oct 18:00 darkk@ updates `generate-streams-import-in-db.sh` to stop ingesting data to luigid pipeline as ssdams storing the data almost maxed out the capacity (~1Gb left)
04 Oct 22:24 darkk@ mailed support request to re-organise data storage chunks
09 Oct 14:13 support responds, data storage is to re-organised, but some of the assumptions regarding storage were wrong, some further work has to be done to revive old pipeline
[ongoing]

What went well:
- monitoring provided alert that we're going to max out capacity

What went wrong:
- legacy system stayed way live longer than expected (and have maxed out the capacity)
- it happened during ongoing Catalonia incident
- people are travelling during the incident response phase, that causes response slowdown 

What is still unclear:
- [ ] how can we improve capacity planning?

Impact: everything died

What could be done to prevent relapse and decrease impact:
- [ ] monitor legacy pipeline failures, `REFRESH MATERIALIZED VIEW` issue was unnoticed for a week

**Comment by hellais** [comment]
I have basically completed implementing the backward compatibility layer for switching legacy explorer over to the new pipeline.

These are the relevant pull requests:

https://github.com/TheTorProject/ooni-explorer/pull/119
https://github.com/TheTorProject/ooni-measurements/pull/46

What I would say is missing to deploy this is:

* [ ] Add the exporting of the metrics I need to be written in `/data/ooni/public/centrifugation` (see: https://github.com/TheTorProject/ooni-pipeline/issues/110)
* [ ] Seeing if it makes sense to export static dumps of other items that are pretty long running queries or if instead we can optimise the queries (see: https://github.com/TheTorProject/ooni-measurements/pull/46/files#diff-265f329362fe5ba30449e09104489be2R168)
* [ ] Solving the issue of wrongly confirmed cases of censorship. More on this below.

What is missing, but I don't consider it necessary for MVP sake is:

* [ ] Adding a compatibility layer with some of the other endpoints that query the legacy pipeline database. These are:
   * [ ] `SELECT * FROM identified_vendors`
   * [ ] `SELECT name FROM asns WHERE asn = $1`
   * [ ] `SELECT * FROM domains WHERE url LIKE $1`

I would say that as the pipeline has been sleeping for over a month we ought to revive it ASAP.

The other thing, that I actually don't know a good solution to, is that now (due to wrong geoip lookup) and the fact that we run the fingerprint on every country (not just the country it's from), leads us to concluding that there is confirmed censorship where there isn't (example: Iran blockpages showing up in Italy or Korean blockpages in the US).

I believe we should fix this before deploying it, because I imagine many people will be upset by it. @darkk do you think you could make the confirmed flag more strict? Or extract it in a different way so that we can filter out these cases?

The alternative "hot-fix" solution that I would propose is that we drop the notion of countries colored red entirely (it was a bad idea anyways) and just color the world based on the number of measurements.

Thoughts?

cc @agrabeli @elioqoshi

**Comment by darkk** [comment]
> Iran blockpages showing up in Italy or Korean blockpages in the US

That may be geoip, that may be censorship leak, that may be whatever else. IMHO the "right" way is to mark that data manually with `confirmed = FALSE` via `label` table after manual review.
Maybe that should be a "process" and not a one-time action.

> drop the notion of countries colored red entirely (it was a bad idea anyways)

I agree, single color for "confirmed censorship cases" is misleading. E.g., should US be red because of `sci-hub.cc` case and/or online gambling laws?... TRICKY!

**Comment by hellais** [comment]
> That may be geoip, that may be censorship leak, that may be whatever else. IMHO the "right" way is to mark that data manually with confirmed = FALSE via label table after manual review.

Right, this would be the ideal thing, but currently this is not something that is very easy to do, nor is it clear how it would be done (is somebody going to build a GUI for it? What is the process? etc.).

So maybe in the interim we can just exclude those from being flagged as confirmed? We should in these cases, set the anomaly flag and maybe some other column saying the country of which the blockpage is detected.

How I understand the "confirmed" flag, is that it's a case in which we are sure that the measurement in question is showing evidence of censorship in that country. Since there is a country mismatch it should not be confirmed.

Or said otherwise, the confirmed claim is a VERY strong one, that we don't take lightly, so we should set it only when we are 100% that the data is verifiably showing evidence of censorship in the country it's in.

**Comment by hellais** [comment]
> I agree, let's drop that.

I did this yesterday in the above linked ooni-explorer PR.

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
