### ISSUE TITLE
Separate critical alerts from non-critical alerts

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#182]
Prometheus and alert manager supports alert levels.

I would find it useful to be able to visually distinguish alerts between the classes:

**1. OMG it's on fire, fix it immediately!**

from

**2. You should eventually look into fixing this**

Examples of 1 are:
* Bouncer is down
* Collectors are down

Examples of 2 are:
* Some machine is low on disk space
* A SSL cert will expire in some weeks

We should annotate these types of alerts with a different `severity` label (see: https://prometheus.io/docs/alerting/rules/#templating), depending on if it's just a warning (so we color it yellow) or a critical alert.

**Comment by darkk** [comment]
I believe that "machine is low on disk space" is still OMG as most of programs can't correctly handle out-of-disk-space case. Broken files should be rather avoided than fixed.
SSLCertExpires is mail-only since 01bf91aa0da69a8c83fdf4c9e231d91145366b68
NTPOutOfSync is also mail-only 141899c5d240f073567b62b5c4a3749b3a12cc70

As soon as we decided to put insistent notifications idea aside, "slack + email" and "rare email" are the two classes of notifications.
