### ISSUE TITLE
bouncer down for 9 hours

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#183]
Impact: everything died

Detection: alert from user

Timeline UTC (28 Oct):
00:00:01 `bouncer CRON[16384]: (root) CMD (/bin/sh /data/renew-certs.sh)`
00:00:04 `Main loop terminated.`
00:00:44 docker fails to start container for unclear reason
```
00:00:44,162:INFO:certbot.hooks:Running post-hook command: cp /etc/letsencrypt/live/bouncer.ooni.io/privkey.pem /etc/letsencrypt/live/bouncer.ooni.io/fullchain.pem /data/bouncer/tls && docker start ooni-backend-bouncer
00:00:44,292:ERROR:certbot.hooks:Hook command "cp /etc/letsencrypt/live/bouncer.ooni.io/privkey.pem /etc/letsencrypt/live/bouncer.ooni.io/fullchain.pem /data/bouncer/tls && docker start ooni-backend-bouncer" returned error code 1
00:00:44,293:ERROR:certbot.hooks:Error output from None:
An error occurred trying to connect: Post http:///var/run/docker.sock/v1.21/containers/ooni-backend-bouncer/start: EOF
Error: failed to start containers: [ooni-backend-bouncer]
```
00:05: AlertManager | [FIRING:1] InstanceDown https://bouncer.ooni.io/bouncer
08:59:27 hellais | damn OONI bouncer is down
09:01:02 `twistd ... starting up.`
09:01:18 darkk | Good morning, yeah.
09:05: AlertManager | [RESOLVED] InstanceDown https://bouncer.ooni.io/bouncer
31 Oct 16:00: incident published

What went wrong:
- yet another certbot wrapper found (sigh)
- nothing new regarding letsencrypt, old story we've seen in other incidents
- 10% of daily measurements volume was lost (rough estimate based on dumb `du`)

What is still unclear:
- what was the reason for the docker to fail container startup?

**Comment by hellais** [comment]
What we should do to prevent this in the future:
* [ ] Migrate bouncer to greenhost or ec2

**Comment by hellais** [comment]
Today there was a relapse. The bouncer was down for 10 minutes.

Timeline (CEST):

Alertbot [15:35]
[FIRING] Instance https://bouncer.ooni.io/bouncer down
https://bouncer.ooni.io/bouncer of job "ooni bouncer" has been down for more than 1 minute.
minute.


hellais [15:38] 
bouncer down
logging in
```root@bouncer:~# uptime
 14:38:21 up 7 min,  1 user,  load average: 0.15, 0.10, 0.06
```
It looks like the machine was rebooted

darkk [15:38] 
@hellais you're fast :slightly_smiling_face:

hellais [15:39] 
Docker didn't come up on reboot
Weird
Not sure if it would have eventually come back up
In any case I did:
```root@bouncer:~# /etc/init.d/docker restart
[....] Restarting docker (via systemctl): docker.service
. ok
```
```root@bouncer:~# docker start aa33f40e801f
aa33f40e801f
```
And it has the stupid docker bug with the pidfile
probably because it didn't clean it up after the force reboot
@darkk do you remember what the hotfix was for this?

darkk [15:42] 
@hellais sure, let me apply it.

hellais [15:43] 
thanks
ha
`find /var/lib/docker/ -name oonib.pid`

AlertManager APP [15:45] 
[RESOLVED] Instance https://bouncer.ooni.io/bouncer down
https://bouncer.ooni.io/bouncer of job "ooni bouncer" has been down for more than 1 minute.

**Comment by darkk** [comment]
Actually, I don't consider it a **relapse**, all the causes are different. But tracking it here is okay :)

**Comment by hellais** [comment]
The bouncer has now been migrated over to greenhost cloud. As the A record propagates clients should start using the new bouncer.

**Comment by hellais** [comment]
I have now stopped the "service" on the grnet bouncer and deleted the onion address keys on that box to avoid confusion.

**Comment by darkk** [comment]
Seems, all the checkboxes have their tickmarks, so I'm closing this incident ticket.
