### ISSUE TITLE
DiskStuck for ~10m at AMS leading to measurements loss

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#266]
Impact: measurements loss for ~10m window

Detection: DiskStuck alert and [lots of others](https://mon.ooni.nu/prometheus/graph?g0.range_input=15m&g0.end_input=2018-12-19%2010%3A15&g0.expr=ALERTS&g0.tab=0)

Timeline UTC (Dec 19):
10:04 disks start to get stuck
10:05:10 first BlackboxDown alert on https://c.collector.ooni.io/invalidpath
10:08 DiskStuck and %iowait alerts start firing
10:13:55 last BlackboxDown alert on https://c.collector.ooni.io/invalidpath
10:14 disks recover

[Nice node_seeksample_timestamp screenshot](https://mon.ooni.nu/prometheus/graph?g0.range_input=15m&g0.end_input=2018-12-19%2010%3A15&g0.expr=node_seeksample_timestamp&g0.tab=0):
![screenshot_2018-12-19 prometheus time series collection and processing server](https://user-images.githubusercontent.com/21046/50214277-e98cbf00-0390-11e9-86ea-1d2b06016bc9.png)

What went well:
- Prometheus is unexpectedly tenacious, it was affected as well, but it was providing steady flow of alerts

What went wrong:

That's a bit unexpected to me that https://c.collector.ooni.io/invalidpath endpoint went down. AFAIK, MK does not spool measurements and does not retry "in a while" on failure (@bassosimone correct me if I'm wrong). Traffic to that endpoint went down "for real":
![screenshot_2018-12-19 grafana - node exporter full single machine](https://user-images.githubusercontent.com/21046/50214542-9cf5b380-0391-11e9-83bd-5f0f4db5e8f6.png)
Also, that's our "main" collector given the volume of traffic. Here is hkgcollectora at the same timeframe:
![screenshot_2018-12-19 grafana - node exporter full single machine 1](https://user-images.githubusercontent.com/21046/50214734-0f669380-0392-11e9-8665-eed7985be9c3.png)
And miacollector:
![screenshot_2018-12-19 grafana - node exporter full single machine 2](https://user-images.githubusercontent.com/21046/50214765-24432700-0392-11e9-9cf6-8d8e8b4434ee.png)

What is still unclear:
- [ ] is HA collector a good response to alike incident or should it be just the OONI Probe slightly more resilient to network failures?

**Comment by bassosimone** [comment]
@darkk it should be more resilient. The first window where to implement this change is v0.10.0 in which I am replacing the collector with a new implementation using CURL.

The possibility of resubmitting measurements that could not be submitted is indeed already part of our roadmap for that release of MK.

What can also be added is that the submission code could retry _immediately_ 2-3 times to submit the measurement if it cannot submit it right away. What is more complex to do in MK, because it has little state saved on disk, is to schedule submitting again for later. I believe this can possibly be done by the app.

Do you have comments on the above? Is there anything else that you would recommend me to consider?

**Comment by darkk** [comment]
> retry immediately 2-3 times

It makes sense if and only if the client got no response from collector at all. Lack of response is _likely_ network failure, while it can also be mismatch of timeout values between frontend and client. But that sort of retry **does not help to mitigate alike incident**.

I think, it's good to do an immediate retry on network error / timeout. I'm not so sure about 5xx. Maybe. More thinking is required.

Also, given that other parts of the Collector / Pipeline / Explorer do not actually expect retries to by best knowledge and, so, do not expect to get duplicate measurements, it may trigger some pathological behavior here and there. So I'm unsure about the best schedule to ship alike feature (shipping that during holidays seems risky).

**Comment by bassosimone** [comment]
Right. The release of MK v0.10.0 is planned for January and will be included by OONI mobile v2.1, which will probably happen in February. So, that would save us from big issues during the holiday.

I agree that retrying immediately does not solve the original issue. I believe there is need for collaboration from the app to do that, as I said above.

I think your commment can be distilled as hinting that retrying immediately only makes sense in case of network error (most likely this would make sense in case of timeout, but we can possibly code it more broadly and it should probably be fine).

Regarding components that do not expect dupes, my understanding was that we should open a new report, when resubmitting, rather than keeping the old report ID. The argument here is that we don’t know whether the original report is already open, therefore using a new report ID aid anyway the robust thing to do.

**Comment by darkk** [comment]
I don't quite understand the reason for "unsent spool" management code to be duplicated for iOS, Android and Desktop instead of putting it into MK.

I understand that it may be not trivial. I also 100% understand that there should be some API for the app to call (I mean something like `mk::upload_stuff_if_you_have_to()`), so collaboration from the app is non-zero as the time to call that entry-point is defined by the app (given user interaction, availability of network, background times or whatever else).

@bassosimone It would be awesome to link here some canonical text explaining that design decision regarding "unsent spool".

**Comment by bassosimone** [comment]
Right. It’s mainly historical. We originally thought of MK as a general library that third parties want to integrate. So, we postulated that MK should not touch the disk.

MK is not a real library. It is OONI’s portable code plus NDT (apart from OONI people only uses MK for NDT). We also have a dedicated library for NDT. Which means we can do more OONI stuff in MK with more freedom, as the general library requirement is relaxed, _as long as_ we keep layers clearly separated such that we can undo changes easily in the future.

Does this text reply to your concerns? Do you feel like I should document this also as a README or other doc in MK sources?

**Comment by darkk** [comment]
I think, that's good. I'd also copy part of Slack conversation to preserve that text (as, I believe, the concept of "unsent messages spool" will eventually be discussed one more time):

> **sbs**
> this is a design choice based on the canonical split between the mechanism and the policy, where we also postulated that MK should not touch the disk, the app should.
> This has since been relaxed to the point where the app tells MK where to write on disk, but MK manages the disk, for probe orchestration. We did this move because it simplified life and increased code velocity.
> **darkk** 
> Yep, that's the tough choice indeed as soon app may also need measurement data [e.g. to display measurement result]
> **sbs**
> I believe it makes sense to have more “portable OONI layers” in MK as it’s becoming clear that people either wants to use OONI or want NDT and there is a separate library for that. So we have less self imposed clean design constraint in MK. I believe we’ll be fine as long as layers are clearly separated and the mechanism is MK is independent of the policy we can select several layers up.
> I also think the best way of sharing info is via JSON files serialised on disk that are not touched anymore by MK after the current blocking operation is over. (Unclear if this fits with the spool model but maybe it does.)
> So, basically we can say that, yes, the spool can also be implemented in MK

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
