### ISSUE TITLE
Incident: very slow rsync between ams-ps1 and datacollector

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/sysadmin#403]
The pipeline was rsyncing files very slowly (< 900 Kbps). The issue was reproduced manually with a low success rate (e.g. less than 10%). The pipeline has been then restarted.

See: https://mon.ooni.nu/grafana/d/AE8tFfxWk/collectors-disk-activity?orgId=1&from=1574881731778&to=1574968131778

**Comment by FedericoCeratto** [comment]
socket status according to ss -nta -p -e -m -i

```ESTAB                    0                         691052                                       37.218.245.109:22                                          37.218.240.67:50052                     users:(("sshd",pid=16772,fd=3),("sshd",pid=16751,fd=3)) timer:(on,240ms,0) ino:4431812 sk:9 <->
	 skmem:(r0,rb359040,t0,tb963072,f32660,w712812,o0,bl0,d1) ts sack reno wscale:7,7 rto:380 rtt:179.943/10.855 ato:40 mss:1448 pmtu:1500 rcvmss:1408 advmss:1448 cwnd:11 ssthresh:5 bytes_acked:1925246329 bytes_received:772097 segs_out:1363340 segs_in:402957 data_segs_out:1349397 data_segs_in:16430 send 708.1Kbps lastsnd:140 lastrcv:490 lastack:140 pacing_rate 849.8Kbps delivery_rate 664.3Kbps busy:24227780ms rwnd_limited:170ms(0.0%) unacked:11 retrans:0/19671 rcv_rtt:175.875 rcv_space:28960 rcv_ssthresh:178060 notsent:675124 minrtt:173
```

**Comment by hellais** [comment]
In order to resolve the incident what we did was the following:

1. `pkill rsync` from the datacollector host and wait for airflow to mark the `fetcher` DAG task as failed
2. Clear the state of the `fetcher` DAG root task as well as the state of the `hist_canning` DAG root task
3. `rsync` had left over some temporary files which had ended up inside of the `2019-11-27` bucket and the `hist_canning` DAG was complaining with:
```
[2019-11-28 18:15:16,623] {base_task_runner.py:95} INFO - Subtask: [2019-11-28 18:15:16,622] {bash_operator.py:94} INFO - __main__.CannerError: ('Unable to parse report filename', '.20191127T060731Z-RU-AS48642-web_connectivity-20191127T060731Z_AS48642_e5Gm6bzrFVhDIlwXGYVmPNdCGpgZdNpnfMLcymVBvacqZMXUXW-0.2.0-probe.json.otkpY7')
```

Initially we tried to just delete the file in question from `/data/ooni/private/reports-raw/2019-11-27`, but then the `hist_canning` was complaining that a shasum was not matching.

This was triggered by the `shasum` inside of `/data/ooni/private/reports-raw-shals/2019-11-27`.

4. We ran from datacollector the following command to rewrite the shals file:
```
find /data/ooni/private/reports-raw/2019-11-27 -type f -printf '%f %s\n' | LC_ALL=C sort --buffer-size=96M | sha256sum > 2019-11-27
```

5. Cleared the state of `hist_canning` and the pipeline restarted normally

**Comment by hellais** [comment]
We can close this as it has been resolved.

**Comment by hellais** [comment]
Here are screenshots on how to resolve this incident:

![Screenshot 2020-01-14 at 17 55 45](https://user-images.githubusercontent.com/424620/72366858-62c52580-36fb-11ea-9f42-479b938ffc16.png)
![Screenshot 2020-01-14 at 17 55 39](https://user-images.githubusercontent.com/424620/72366859-62c52580-36fb-11ea-80c6-023149387de2.png)
![Screenshot 2020-01-14 at 17 05 01](https://user-images.githubusercontent.com/424620/72366860-635dbc00-36fb-11ea-8c84-0735ddc3a9d6.png)
![Screenshot 2020-01-14 at 17 04 56](https://user-images.githubusercontent.com/424620/72366861-635dbc00-36fb-11ea-9c39-18dce3e9ad62.png)
![Screenshot 2020-01-14 at 17 04 51](https://user-images.githubusercontent.com/424620/72366863-635dbc00-36fb-11ea-83c2-40d2a8bbb499.png)
![Screenshot 2020-01-14 at 17 04 45](https://user-images.githubusercontent.com/424620/72366864-635dbc00-36fb-11ea-8d5a-32d152613886.png)
